language: java
jdk: oraclejdk8

branches:
  only:
    - master
    - 1.0.0-SNAPSHOT
script: 
	- mvn -B verify # -B batch mode makes Maven less verbose
    - mvn deploy -s maven-settings.xml -DskipTests	
cache:
  directories:
    - '$HOME/.m2/repository'
